---
title: ACM enf
author: "Élodie Lemaire"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
    pdf_document:
header-includes:
  - \usepackage[normal,labelfont=bf]{caption}
  - \usepackage[bottom]{footmisc}
  - \usepackage{mdframed}
linestretch: 1.5
fontsize: 12
mainfont: Times
urlcolor: blue
lang: fr
---

```{r setup, include=FALSE}
setwd("/Users/elodielemaire/Desktop/Mémoire M2")
knitr::opts_chunk$set(
	echo = FALSE,
	fig.align = "center",
	message = FALSE,
	warning = FALSE
)
library(pacman)
p_load(tidyverse, questionr, FactoMineR, Factoshiny, survey, missMDA, knitr, 
       explor, webshot, gtsummary, gt, survey, factoextra, magrittr,
       MetBrewer, extrafont, huxtable)
theme_gtsummary_language("fr", decimal.mark = ",", big.mark = " ")
```

```{r source}
source("Recodage.R")
source("R markdown/R/Fonctions.R")
```

```{r recodage}
s_mecs <- sor %>% subset(CATEG_rec == "MECS")
s_mecs$id <- rownames(s_mecs)

s_acm <- s_mecs %>% 
  select("HEBE_rec3","ARES_rec", "SRES_rec", "id")%>% 
  drop_na()

levels(s_acm$HEBE_rec3) <- paste0("hebe_",levels(s_acm$HEBE_rec3))

levels(s_acm$ARES_rec) <- paste0("ares_",levels(s_acm$ARES_rec))

levels(s_acm$SRES_rec) <- paste0("sres_",levels(s_acm$SRES_rec))

var_activ  <- s_acm[,c("ARES_rec", "HEBE_rec3", "SRES_rec")]
```

```{r}
res.MCA<-MCA(var_activ,graph=FALSE)
plot.MCA(res.MCA,invisible= 'ind',title="Graphe de l'ACM",label =c('var','quali.sup'))

g2 <- plot.MCA(res.MCA,invisible= c( 'quali.sup'),
               title="Espace des types d'hébergements en MECS",
               autoLab = "yes",
               graph.type = "ggplot", col.ind = "skyblue",
               col.var = "#4c3b7f", col.quali.sup = "#88a0dc")
g2  + labs(caption="Source : Enquête ES-PE 2017, DREES \n Champ : France entière, hors Mayotte, enfants sortis de l’établissement \n d’observation au cours de 2017 (hors sections d’accueil mères-enfants).")+
  theme(text = element_text(family = "Times"), plot.title = element_text(face = "bold"))

fviz_screeplot(res.MCA, addlabels = TRUE, ylim =c(0, 50), main="", ylab = "Pourcentages d'inertie") + theme_bw() +
  theme(text = element_text(family = "Times"))

```


```{r}
res.MCA2<-MCA(var_activ,ncp=2,graph=FALSE)
res.HCPC2<-HCPC(res.MCA2,nb.clust=3, consol = TRUE, graph=FALSE)
plot.HCPC(res.HCPC2, choice = "tree", title = "")

s_acm$grp2 <- res.HCPC2$data.clust$clust
```

```{r}
s_acm2 <- merge(s_acm, s_mecs, by = "id")

## Réordonnancement de s_acm2$ARES_rec.x
s_acm2$ARES_rec.x <- s_acm2$ARES_rec.x %>%
  fct_relevel(
    "ares_EtabASEPJJ", "ares_Logtacc", "ares_Logthors", "ares_Assfam",
    "ares_Famille")

s_acm2$SRES_rec.x <- s_acm2$SRES_rec.x %>%
  fct_relevel(
    "sres_EtabASEPJJ", "sres_Logtacc", "sres_Logthors", "sres_Assfam",
    "sres_Famille")

s_acm2 %>% tbl_summary(include = c(grp2, ARES_rec.x, HEBE_rec3.x,SRES_rec.x),
                    by = grp2,
                    percent = "col", 
                    statistic = list(all_categorical() ~ "{p}")) %>%   
  modify_header(label = " ") %>% 
  bold_labels() %>% 
  modify_spanning_header(c("stat_1", "stat_2","stat_3") ~ "**Groupe de la classification**") %>% 
  add_overall()
```


```{r}
s_acm2$MES_rec <-
  fct_recode(as.character(s_acm2$MES_rec),
    NULL = "NA")

s_acm2 %>% tbl_summary(include = c(grp2, age_ed,age_sd,SEX,MNA, HAND),
                    by = grp2,
                    percent = "col", 
                    statistic = list(all_categorical() ~ "{p}"),
                    missing = "no",) %>%   
  modify_header(label = " ") %>% 
  bold_labels() %>% 
  modify_spanning_header(c("stat_1", "stat_2","stat_3") ~ "**Groupe de la classification**") %>% 
  add_overall()


## Réordonnancement de s_acm2$MES_rec
s_acm2$MES_rec <- s_acm2$MES_rec %>%
  fct_relevel(
    "Mesure touchant la responsabilité parentale", "Mesure administrative Mineur",
    "Mesure administrative Jeune Majeur", "Judiciaire confié", "Judiciaire direct juge",
    "MO.autre"
  )
s_acm2 %>% tbl_summary(include = c(grp2, MES_rec),
                    by = grp2,
                    percent = "row", 
                    statistic = list(all_categorical() ~ "{p}"),
                    missing = "no") %>%   
  modify_header(label = " ") %>% 
  bold_labels() %>% 
  modify_spanning_header(c("stat_1", "stat_2","stat_3") ~ "**Groupe de la classification**")

s_acm2%>% tbl_summary(include = c(grp2, dur_dpla, dur_pla),
                    by = grp2,
                    percent = "col", 
                    statistic = list(all_continuous() ~ "{mean}"),
                    missing = "no",) %>%   
  modify_header(label = " ") %>% 
  bold_labels() %>% 
  modify_spanning_header(c("stat_1", "stat_2","stat_3") ~ "**Groupe de la classification**")


## Recodage de s_acm2$hebe_capa2
s_acm2$hebe_capa2 <- s_acm2$hebe_capa2 %>%
  fct_recode(
    "deux" = "assfam et domicile",
    "trois" = "autonom, assfam et domicile"
  )
s_acm2%>% tbl_summary(include = c(hebe_capa2),
                    by = grp2,
                    percent = "row", 
                    statistic = list(all_categorical() ~ "{p}"),
                    missing = "no",) %>%   
  modify_header(label = " ") %>% 
  bold_labels() %>% 
  modify_spanning_header(c("stat_1", "stat_2","stat_3") ~ "**Groupe de la classification**")


s_acm2%>% tbl_summary(include = c(ppla),
                    by = grp2,
                    percent = "col", 
                    statistic = list(all_categorical() ~ "{p}"),
                    missing = "no",) %>%   
  modify_header(label = " ") %>% 
  bold_labels() %>% 
  modify_spanning_header(c("stat_1", "stat_2","stat_3") ~ "**Groupe de la classification**")
```

```{r}
modele <- s_acm2 %>% select(poids_sor, ID, SEX, MNA, HAND, age_ed, age_sd, MES_rec,hebe_capa2, grp2, ppla, age_s, age_e)

modele %<>% drop_na()

recode_age2 <- function(var) {
  print(table(var, useNA = "ifany"))
  var_rec <- cut(var,
                 include.lowest = TRUE,
                 right = FALSE,
                 dig.lab = 4,
                 breaks = c(0, 11, 13, 15, 18, 27)
  )
  var_rec <- var_rec %>%
    fct_recode("0 à 10 ans" = "[0,11)", "11 à 12 ans" = "[11,13)", "13 à 14 ans" = "[13,15)", "15 à 17 ans" = "[15,18)", "18 ans à plus" = "[18,27]")
  print(table(var_rec, useNA = "ifany"))
  return(var_rec)
}

modele$age_sd2 <- recode_age2(modele$age_s)
modele$age_ed2 <- recode_age2(modele$age_e)

modele %>% tbl_summary(include = c(SEX, MNA, HAND, age_ed, age_sd2, MES_rec, hebe_capa2, ppla),
                    by = grp2,
                    missing = "no",
                    statistic = list(all_categorical() ~ "{n}")) %>%   
  modify_header(label = "") %>% 
  bold_labels()

require(nnet)
m1 <- multinom(grp2 ~ SEX + age_ed2 + age_sd2  + MNA + HAND, data = modele)

m1 %>% tbl_regression(exponentiate = TRUE) %>% 
  add_significance_stars(hide_se = TRUE, hide_ci = TRUE) %>%
  modify_header(label = "**Référence : grp1**") %>%
  modify_caption("Modèle 1 réduit : type d'hébergement à la sortie de MECS")  %>% 
  modify_column_hide("ci") %>% 
  bold_labels()%>%
  multinom_pivot_wider()


## Réordonnancement de modele$MES_rec
modele$MES_rec <- modele$MES_rec %>%
  fct_relevel(
   "Autre", "Mileu ouvert", "Mesure touchant la responsabilité parentale",
    "Mesure administrative Mineur", "Mesure administrative Jeune Majeur",
    "Judiciaire confié", "Judiciaire direct juge"
  )
m2 <- multinom(grp2 ~ SEX + age_ed2 + age_sd2  + MES_rec +MNA + HAND, data = modele)

m2 %>% tbl_regression(exponentiate = TRUE) %>% 
  add_significance_stars(hide_se = TRUE, hide_ci = TRUE) %>%
  modify_header(label = "**Référence : grp1**") %>%
  modify_caption("Modèle 2 : type d'hébergement à la sortie de MECS")  %>% 
  modify_column_hide("ci") %>% 
  bold_labels()%>%
  multinom_pivot_wider()


m3 <- multinom(grp2 ~ SEX + age_ed2 + age_sd2  + MES_rec +MNA + HAND + ppla, data = modele)

m3 %>% tbl_regression(exponentiate = TRUE) %>% 
  add_significance_stars(hide_se = TRUE, hide_ci = TRUE) %>%
  modify_header(label = "**Référence : grp1**") %>%
  modify_caption("Modèle 2 : type d'hébergement à la sortie de MECS")  %>% 
  modify_column_hide("ci") %>% 
  bold_labels()%>%
  multinom_pivot_wider()


modele$ppla <- as.numeric(modele$ppla)

m4 <- multinom(grp2 ~ SEX + age_ed2 + age_sd2  + MES_rec +MNA + HAND  + ppla+ hebe_capa2, data = modele)
step(m4)

m4 %>% tbl_regression(exponentiate = TRUE) %>% 
  add_significance_stars(hide_se = TRUE, hide_ci = TRUE) %>%
  modify_header(label = "**Référence : grp1**") %>%
  modify_caption("Modèle 2 : type d'hébergement à la sortie de MECS")  %>% 
  modify_column_hide("ci") %>% 
  bold_labels()%>%
  multinom_pivot_wider()

## Réordonnancement de modele$grp2
modele$grp2 <- modele$grp2 %>%
  fct_relevel(
    "2", "1", "3"
  )

m4 <- multinom(grp2 ~ SEX + age_ed2 + age_sd2  + MES_rec +MNA + HAND  + ppla+ hebe_capa2, data = modele)
step(m4)

m4 %>% tbl_regression(exponentiate = TRUE) %>% 
  add_significance_stars(hide_se = TRUE, hide_ci = TRUE) %>%
  modify_header(label = "**Référence : grp1**") %>%
  modify_caption("Modèle 2 : type d'hébergement à la sortie de MECS")  %>% 
  modify_column_hide("ci") %>% 
  bold_labels()%>%
  multinom_pivot_wider()
```

