---
title: "Calculs"
author: "Élodie Lemaire"
date: '2022-06-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE,fig.align = 'center')
library(pacman)
p_load(tidyverse, questionr, FactoMineR, Factoshiny, survey, missMDA, knitr, 
       explor, webshot, gtsummary, gt, survey, factoextra, magrittr,GGally,wesanderson,
       MetBrewer, extrafont, huxtable)
theme_gtsummary_language("fr", decimal.mark = ",", big.mark = " ")
```


```{r}
source("Recodage.R")
source("Fonctions.R")
```

# Statut de réponse des établissements

```{r}
obs$CATEG_rec2 <- add_n(obs$CATEG_rec)
g1 <- ggplot(na.omit(obs)) +
  aes(x = CATEG_rec, fill = STATUT_REP, by = CATEG_rec, label = f(after_stat(prop))) +
  geom_bar(position = "fill") +
  geom_text(stat = "prop", position = position_fill(.5), colour = "white", size = 3.5) +
  scale_fill_manual(values = wes_palette("Darjeeling1")) +
  xlab("Type d'établissement") +
  ylab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  coord_flip() +
  theme_bw() +
  theme(legend.position = "top") +
  labs(fill = "Statut de réponse :")
g1 + theme(text = element_text(family = "Times"), plot.caption = element_text(face = "italic"))
```

# Répartition des enfants accueillis

```{r}
enf$CATEG_rec <- enf$CATEG_rec %>% fct_relevel("MECS", "Foyers", "Lieux de vie", "Villages", "Pouponnières")
enfw <- svydesign(ids = ~1, data = enf, weights = ~ enf$poids2)

enfw %>% tbl_svysummary(include = c(CATEG_rec,SEX, age_ed, MNA,HAND),
                    by = CATEG_rec,
                    percent = "col", 
                    statistic = list(all_categorical() ~ "{p}"),
                    missing = "no") %>%   
  modify_header(label = "") %>% 
  modify_header(all_stat_cols() ~ "**{level}**, N = {n_unweighted}") %>% 
  bold_labels()


sor$CATEG_rec <- sor$CATEG_rec %>% fct_relevel("MECS", "Foyers", "Lieux de vie", "Villages", "Pouponnières")
sorw <- svydesign(ids = ~1, data = sor, weights = ~ sor$poids2)

sorw %>% tbl_svysummary(include = c(CATEG_rec,SEX, age_ed, MNA,HAND),
                    by = CATEG_rec,
                    percent = "col", 
                    statistic = list(all_categorical() ~ "{p}"),
                    missing = "no") %>%   
  modify_header(label = "") %>% 
  modify_header(all_stat_cols() ~ "**{level}**, N = {n_unweighted}") %>% 
  bold_labels()
```


# Répartition par mesures 

```{r}
enfw <- svydesign(ids = ~1, data = enf, weights = ~ enf$poids2)

enfw %>% tbl_svysummary(include = c(MES_rec, CATEG_rec),
                    by = CATEG_rec,
                    percent = "col", 
                    statistic = list(all_categorical() ~ "{p}"),
                    missing = "no") %>%   
  modify_header(label = "") %>% 
  modify_header(all_stat_cols() ~ "**{level}**, N = {n_unweighted}") %>% 
  bold_labels() %>%
  add_p()

sorw <- svydesign(ids = ~1, data = sor, weights = ~ sor$poids2)

sorw %>% tbl_svysummary(include = c(MES_rec, CATEG_rec),
                    by = CATEG_rec,
                    percent = "row", 
                    statistic = list(all_categorical() ~ "{p}"),
                    missing = "no") %>%   
  modify_header(label = "") %>% 
  modify_header(all_stat_cols() ~ "**{level}**, N = {n_unweighted}") %>% 
  bold_labels()

t1 <- svytable(~CATEG_rec + MES_rec, sorw)
t1 <-  t1[-4,]
t1 <-  t1[-4,]
chisq.test(t1)
```

# Ancienneté par mois 

```{r}
enfw %>% tbl_svysummary(include = c(dur_dpla, CATEG_rec),
                    by = CATEG_rec,
                    percent = "col", 
                    statistic = list(all_continuous() ~ "Q1 : {p25}, Med : {median}, Moy : {mean}, Q3 : {p75}"),
                    missing = "no") %>%   
  modify_header(label = "") %>% 
  modify_header(all_stat_cols() ~ "**{level}**, N = {n_unweighted}") %>% 
  bold_labels()

sorw %>% tbl_svysummary(include = c(dur_dpla, CATEG_rec),
                    by = CATEG_rec,
                    percent = "col", 
                    statistic = list(all_continuous() ~ "Q1 : {p25}, Med : {median}, Moy : {mean}, Q3 : {p75}"),
                    missing = "no") %>%   
  modify_header(label = "") %>% 
  modify_header(all_stat_cols() ~ "**{level}**, N = {n_unweighted}") %>% 
  bold_labels()
```
# Répartition critères déclarés par les établissements

```{r}
act2 <- filter(act, CATEG_rec != "Villages")
act2 <- filter(act2,CATEG_rec != "Pouponnières")

act2$CATEG_rec <- act2$CATEG_rec %>%
  fct_relevel("MECS", "Foyers", "Lieux de vie")

act2$poids2<- act2$poids_act/mean(act2$poids_act)
actw <- svydesign(ids = ~1, data = act2, weights = ~ act2$poids2)

actw %>% tbl_svysummary(include = c(REPSEX, REPAGE,REPFRA,REPPED, REPDUR, REPCIV, REPAUC, CATEG_rec),
                    by = CATEG_rec,
                    missing = "no",
                    percent = "col",
                    statistic = list(all_categorical() ~ "{p}"),
                    label = list(REPSEX ~ "par sexe",
                                 REPAGE ~ "par âge",
                                 REPFRA~ "par fratries",
                                 REPPED ~ "par projet pédagogique",
                                 REPDUR ~"par durée du placement",
                                 REPCIV ~"par civil ou pénal",
                                 REPAUC ~"Aucun critère")) %>%   
  modify_header(label = "**Répartition entre les hébergements...**") %>% 
  modify_header(all_stat_cols() ~ "**{level}**, N = {n_unweighted}") %>% 
  modify_column_hide(columns = c(stat_4, stat_5)) %>% 
  bold_labels()
```

# Accueil séquentiel

```{r}
enf$SEQ_rec <- enf$SEQ %>%
  as.character() %>%
  fct_recode(
    "Complet" = "1",
    "Séquentiel" = "2",
    "Diversifié" = "3")

enfw <- svydesign(ids = ~1, data = enf, weights = ~ enf$poids2)
enfw %>% tbl_svysummary(include = c(SEQ_rec, CATEG_rec),
                    by = CATEG_rec,
                    missing = "no",
                    statistic = list(all_categorical() ~ "{p}")) %>%   
  modify_header(label = "") %>% 
  modify_header(all_stat_cols() ~ "**{level}**, N = {n_unweighted}") %>% 
  modify_column_hide(columns = c(stat_4, stat_5)) %>% 
  bold_labels()

t1 <- svytable(~CATEG_rec + SEQ_rec, enfw)
t1 <-  t1[-4,]
t1 <-  t1[-4,]
chisq.test(t1)

enfw %>% tbl_svysummary(include = c(hebe_capa2, CATEG_rec),
                    by = CATEG_rec,
                    missing = "no",
                    statistic = list(all_categorical() ~ "{p}")) %>%   
  modify_header(label = "") %>% 
  modify_header(all_stat_cols() ~ "**{level}**, N = {n_unweighted}") %>% 
  modify_column_hide(columns = c(stat_4, stat_5)) %>% 
  bold_labels()


enfw %>% tbl_svysummary(include = c(hebe_capa2),
                    by = HEBE_rec3,
                    missing = "no",
                    percent = "row", 
                    statistic = list(all_categorical() ~ "{p}")) %>%   
  modify_header(label = "") %>% 
  modify_header(all_stat_cols() ~ "**{level}**, N = {n_unweighted}") %>% 
  bold_labels()  %>% 
  add_p()

chisq.test(svytable(~hebe_capa2+HEBE_rec3, enfw))
chisq.residuals(svytable(~hebe_capa2+HEBE_rec3, enfw))
```

# public accueilli projet d'établissement

```{r}
recode_acc <- function(var) {
  var_recodee <- fct_recode(as.factor(var),
                            "Spécialisé dans l'accueil de ce public" = "1",
                            "Accueil possible" = "2",
                            "Exclusion de ce public"= "3")
  return(var_recodee)
}

act2$ACCSCO <- recode_acc(act2$ACCSCO)
act2$ACCPSY <- recode_acc(act2$ACCPSY)
act2$ACCHAN<- recode_acc(act2$ACCHAN)
act2$ACCDEL <- recode_acc(act2$ACCDEL)
act2$ACCPSY <- recode_acc(act2$ACCADD)
act2$ACCMUL <- recode_acc(act2$ACCMUL)
act2$ACCFRA <- recode_acc(act2$ACCFRA)
act2$ACCMIE <- recode_acc(act2$ACCMIE)
act2$ACCENC <- recode_acc(act2$ACCENC)

actw <- svydesign(ids = ~1, data = act2, weights = ~ act2$poids2)
actw %>% tbl_svysummary(include = c(ACCPSY,ACCHAN,ACCDEL,ACCMUL,ACCFRA,ACCMIE,CATEG_rec),
                    by = CATEG_rec,
                    missing = "no",
                    statistic = list(all_categorical() ~ "{p}")) %>%   
  modify_header(label = "") %>% 
  modify_header(all_stat_cols() ~ "**{level}**, N = {n_unweighted}") %>% 
  modify_column_hide(columns = c(stat_4, stat_5)) %>%
  bold_labels()
```
# Flux 

```{r}
e_mecs <- subset(enf, CATEG_rec == "MECS")

## Recodage de e_mecs$HEBE_rec3
e_mecs$HEBE_rec3 <- e_mecs$HEBE_rec3 %>%
  fct_recode(
    "Collectif" = "Collect",
    "Éclaté" = "Autonomautre",
    "Assistant familial" = "Assfam")

## Recodage de e_mecs$ARES_rec
e_mecs$ARES_rec <- e_mecs$ARES_rec %>%
  fct_recode(
    "Assistant familial" = "Assfam",
    "Logt accompagné" = "Logtacc",
    "Logt hors" = "Logthors",
    "Établissement" = "EtabASEPJJ")

## Réordonnancement de e_mecs$HEBE_rec3
e_mecs$HEBE_rec3 <- e_mecs$HEBE_rec3 %>%
  fct_relevel(
    "Collectif", "Assistant familial", "Domicile", "Éclaté"
  )

## Réordonnancement de e_mecs$ARES_rec
e_mecs$ARES_rec <- e_mecs$ARES_rec %>%
  fct_relevel(
    "Établissement", "Assistant familial", "Famille", "Logt accompagné",
    "Logt hors", "Autres"
  )

e_mecs$poids2 <- e_mecs$poids_enf/mean(e_mecs$poids_enf)
e_mecs$ARES_rec <- as.factor(e_mecs$ARES_rec)

e_mecsw <- svydesign(ids = ~1, data = e_mecs, weights = ~ e_mecs$poids2)

freq(table(e_mecs$HEBE_rec3, useNA = "ifany"))
freq(wtd.table(e_mecs$HEBE_rec3, weights = e_mecs$poids2, useNA = "ifany"))

freq(table(e_mecs$ARES_rec, useNA = "ifany"))
freq(wtd.table(e_mecs$ARES_rec, weights = e_mecs$poids2, useNA = "ifany"))


# Le type d’hébergement en MECS en fonction du type d’hébergement avant l’entrée en MECS pour les enfants présents en 2017
e_mecsw %>% tbl_svysummary(include = c(ARES_rec, HEBE_rec3),
                    by = HEBE_rec3,
                    missing = "no",
                    percent = "row",
                    statistic = list(all_categorical() ~ "{p}")) %>%   
  modify_header(label = "") %>% 
  modify_header(all_stat_cols() ~ "**{level}**, N = {n_unweighted}") %>% 
  bold_labels()

chisq.test(svytable(~ARES_rec +HEBE_rec3, e_mecsw)[,-4])
chisq.residuals(svytable(~ARES_rec +HEBE_rec3, e_mecsw)[,-4])
```

```{r}
s_mecs <- subset(sor, CATEG_rec == "MECS")

# Recodage de s_mecs$HEBE_rec3
s_mecs$HEBE_rec3 <- s_mecs$HEBE_rec3 %>%
  fct_recode(
    "Collectif" = "Collect",
    "Éclaté" = "Autonomautre",
    "Assistant familial" = "Assfam")

## Recodage de s_mecs$ARES_rec
s_mecs$SRES_rec <- s_mecs$SRES_rec %>%
  fct_recode(
    "Assistant familial" = "Assfam",
    "Logt accompagné" = "Logtacc",
    "Logt hors" = "Logthors",
    "Établissement" = "EtabASEPJJ")

## Réordonnancement de s_mecs$HEBE_rec3
s_mecs$HEBE_rec3 <- s_mecs$HEBE_rec3 %>%
  fct_relevel(
    "Collectif", "Assistant familial", "Domicile", "Éclaté"
  )

## Réordonnancement de s_mecs$ARES_rec
s_mecs$SRES_rec <- s_mecs$SRES_rec %>%
  fct_relevel(
    "Établissement", "Assistant familial", "Famille", "Logt accompagné",
    "Logt hors", "Autres"
  )

s_mecs$poids2 <- s_mecs$poids_sor/mean(s_mecs$poids_sor)
s_mecsw <- svydesign(ids = ~1, data = s_mecs, weights = ~ s_mecs$poids2)

freq(table(s_mecs$HEBE_rec3, useNA = "ifany"))
freq(wtd.table(s_mecs$HEBE_rec3, weights = s_mecs$poids2, useNA = "ifany"))

freq(table(s_mecs$SRES_rec, useNA = "ifany"))
freq(wtd.table(s_mecs$SRES_rec, weights = s_mecs$poids2, useNA = "ifany"))
#Le type d’hébergement juste à la sortie de MECS en fonction du type d’hébergement en MECS pour les enfants sortis en 2017
s_mecsw %>% tbl_svysummary(include = c(SRES_rec, HEBE_rec3),
                    by = SRES_rec,
                    percent = "row",
                    missing = "no",
                    statistic = list(all_categorical() ~ "{p}")) %>%   
  modify_header(label = "") %>% 
  modify_header(all_stat_cols() ~ "**{level}**, N = {n_unweighted}") %>% 
  bold_labels()

chisq.test(svytable(~HEBE_rec3 +SRES_rec, s_mecsw)[,-4])
chisq.residuals(svytable(~HEBE_rec3 +SRES_rec, s_mecsw)[,-4])
```


```{r}
ggsurvey(na.omit(e_mecsw)) +
  aes(x = ARES_rec, fill = HEBE_rec3, label = f(after_stat(prop))) +
  geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  labs(fill = "Hébergement en MECS") +
  theme_bw()+ 
  theme(text = element_text(family = "Times"),legend.position="top")
```


```{r}
pct <- freq(svytable(~HEBE_rec3,e_mecsw))[,c(2)]
pct2<- paste0(levels(e_mecs$HEBE_rec3),", ", pct, "%")
e_mecs$HEBE_rec3_e <- e_mecs$HEBE_rec3
levels(e_mecs$HEBE_rec3_e) <- pct2

pct <- freq(svytable(~ARES_rec,e_mecsw))[,c(2)]
pct2 <- paste0(levels(e_mecs$ARES_rec),", ", pct, "%")
e_mecs$ARES_rec_e <- e_mecs$ARES_rec
levels(e_mecs$ARES_rec_e) <- pct2

table(e_mecs$HEBE_rec3_e)
table(e_mecs$ARES_rec_e)

require(ggalluvial)

f1 <- ggplot(na.omit(e_mecs)) +
  aes(axis1 = ARES_rec_e, axis2 = HEBE_rec3_e) +
  scale_x_discrete(limits = c("Avant l'entrée en MECS (ARES)", "En MECS (HEBE)"), expand = c(.1, .05)) +
  scale_y_continuous(labels = NULL) +
  xlab("") +
  ylab("") +
  geom_alluvium(aes(fill = ARES_rec)) +
  geom_flow() +
  geom_stratum(alpha = .5) +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_fill_manual(values = met.brewer("Klimt")) +
  labs(fill = "Type d'hébergement avant MECS:") +
  theme_bw() +
  theme(legend.position = "top")

f1 + theme(text = element_text(family = "Times"))
```

```{r}
require(srvyr)

e_mecsw2 <- e_mecs %>%
  select(HEBE_rec3, ARES_rec, age_ed, poids2)%>% 
  as_survey_design(ids = 1, weight  = poids2)

e_mecsw2<- e_mecsw2 %>% 
  drop_na()

g1 <- e_mecsw2 %>% subset(age_ed == "0_3") %>% 
  ggsurvey() +
  aes(x = ARES_rec, fill = HEBE_rec3) +
  geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  ggtitle("Âge 0 à 3 ans")+ theme(text = element_text(family = "Times", size = 12),legend.position="none")

g2 <- e_mecsw2 %>% subset(age_ed == "4_6") %>% 
  ggsurvey() +
  aes(x = ARES_rec, fill = HEBE_rec3) +
  geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  ggtitle("Âge 4 à 6 ans")+ theme(text = element_text(family = "Times", size = 12),legend.position="none")

g3 <- e_mecsw2 %>% subset(age_ed == "7_12") %>% 
  ggsurvey() +
  aes(x = ARES_rec, fill = HEBE_rec3) +
   geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  ggtitle("Âge 7 à 12 ans")+ theme(text = element_text(family = "Times", size = 12),legend.position="none")

g4 <-e_mecsw2 %>% subset(age_ed == "13_14") %>% 
  ggsurvey() +
  aes(x = ARES_rec, fill = HEBE_rec3) +
   geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  ggtitle("Âge 13 à 14 ans")+ theme(text = element_text(family = "Times", size = 12),legend.position="none")

g5 <-e_mecsw2 %>% subset(age_ed == "15_17") %>% 
  ggsurvey() +
  aes(x = ARES_rec, fill = HEBE_rec3) +
   geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  ggtitle("Âge 15 à 17 ans")+ theme(text = element_text(family = "Times", size = 12),legend.position="none")

g6 <- e_mecsw2 %>% subset(age_ed == "18_+") %>% 
  ggsurvey() +
  aes(x = ARES_rec, fill = HEBE_rec3) +
   geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  labs(fill = "Hébergement en MECS") +
  ggtitle("Âge 18 ans à plus")+ theme(text = element_text(family = "Times", size = 12), legend.position = "top") 

g6_leg <- get_legend(g6)

require(ggpubr)
ggarrange(g1,g2,g3,g4,g5,g6, common.legend = T, legend.grob = g6_leg)
```


```{r}
require(srvyr)
s_mecsw2 <- s_mecs %>%
  select(HEBE_rec3, SRES_rec, age_sd, poids2)%>% 
  as_survey_design(ids = 1, weight  = poids2)

s_mecsw2<- s_mecsw2 %>% 
  drop_na()

g1 <- s_mecsw2 %>% subset(age_sd == "0_3") %>% 
  ggsurvey() +
  aes(x = HEBE_rec3, fill = SRES_rec) +
  geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Archambault")) +
  theme_bw() +
  ggtitle("Âge 0 à 3 ans")+ theme(text = element_text(family = "Times", size = 12),legend.position="none")

g2 <- s_mecsw2 %>% subset(age_sd == "4_6") %>% 
  ggsurvey() +
  aes(x = HEBE_rec3, fill = SRES_rec) +
  geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Archambault")) +
  theme_bw() +
  ggtitle("Âge 4 à 6 ans")+ theme(text = element_text(family = "Times", size = 12),legend.position="none")

g3 <- s_mecsw2 %>% subset(age_sd == "7_12") %>% 
  ggsurvey() +
  aes(x = HEBE_rec3, fill = SRES_rec) +
   geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Archambault")) +
  theme_bw() +
  ggtitle("Âge 7 à 12 ans")+ theme(text = element_text(family = "Times", size = 12),legend.position="none")

g4 <-s_mecsw2 %>% subset(age_sd == "13_14") %>% 
  ggsurvey() +
  aes(x = HEBE_rec3, fill = SRES_rec) +
   geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Archambault")) +
  theme_bw() +
  ggtitle("Âge 13 à 14 ans")+ theme(text = element_text(family = "Times", size = 12),legend.position="none")

g5 <-s_mecsw2 %>% subset(age_sd == "15_17") %>% 
  ggsurvey() +
  aes(x = HEBE_rec3, fill = SRES_rec) +
   geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Archambault")) +
  theme_bw() +
  ggtitle("Âge 15 à 17 ans")+ theme(text = element_text(family = "Times", size = 12),legend.position="none")

g6 <-s_mecsw2 %>% subset(age_sd == "18_+") %>% 
  ggsurvey() +
  aes(x = HEBE_rec3, fill = SRES_rec) +
   geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Archambault")) +
  theme_bw() +
  labs(fill = "Hébergement à la sortie de MECS") +
  ggtitle("Âge 18 ans à plus")+ theme(text = element_text(family = "Times", size = 12), legend.position = "top") 

g6_leg <- get_legend(g6)

require(ggpubr)
ggarrange(g1,g2,g3,g4,g5,g6, common.legend = T, legend.grob = g6_leg)
```

```{r}
## Recodage de e_mecs$MNA
e_mecs$MNA <- e_mecs$MNA %>%
  as.character() %>%
  fct_recode(
    "Non" = "0",
    "Oui" = "1"
  )

## Recodage de e_mecs$MES_rec
e_mecs$MES_rec <- e_mecs$MES_rec %>%
  fct_recode(
    "NULL" = "NA"
  )

e_mecsw <- e_mecs %>%
  as_survey_design(ids = 1, weight  = poids2)

e_mecsw %>% tbl_svysummary(include = c(MES_rec, HEBE_rec3),
                    by = HEBE_rec3,
                    percent = "row",
                    missing = "no",
                    statistic = list(all_categorical() ~ "{p}")) %>%   
  modify_header(label = "") %>% 
  modify_header(all_stat_cols() ~ "**{level}**, N = {n_unweighted}") %>% 
  bold_labels()

```

```{r}
g1 <- e_mecsw2 %>% subset(age_ed == "0_3") %>% 
  drop_na() %>% 
  ggsurvey() +
  aes(x = HEBE_rec3, fill = MNA, label = f(after_stat(prop))) +
  geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  ggtitle("Âge 0 à 3 ans")+ theme(text = element_text(family = "Times"),legend.position="none")

g2 <- e_mecsw2 %>% subset(age_ed == "4_6") %>% 
  drop_na() %>% 
  ggsurvey() +
  aes(x = HEBE_rec3, fill = MNA, label = f(after_stat(prop))) +
  geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  ggtitle("Âge 4 à 6 ans")+ theme(text = element_text(family = "Times"),legend.position="none")

g3 <- e_mecsw2 %>% subset(age_ed == "7_12") %>% 
  drop_na() %>% 
  ggsurvey() +
  aes(x = HEBE_rec3, fill = MNA, label = f(after_stat(prop))) +
   geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  ggtitle("Âge 7 à 12 ans")+ theme(text = element_text(family = "Times"),legend.position="none")

g4 <-e_mecsw2 %>% subset(age_ed == "13_14") %>% 
  drop_na() %>% 
  ggsurvey() +
  aes(x = HEBE_rec3, fill = MNA, label = f(after_stat(prop))) +
   geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  ggtitle("Âge 13 à 14 ans")+ theme(text = element_text(family = "Times"),legend.position="none")

g5 <-e_mecsw2 %>% subset(age_ed == "15_17") %>% 
  drop_na() %>% 
  ggsurvey() +
  aes(x = HEBE_rec3, fill = MNA, label = f(after_stat(prop))) +
   geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  ggtitle("Âge 15 à 17 ans")+ theme(text = element_text(family = "Times"),legend.position="none")

g6 <-e_mecsw2 %>% subset(age_ed == "18_+") %>% 
  drop_na() %>% 
  ggsurvey() +
  aes(x = HEBE_rec3, fill = MNA, label = f(after_stat(prop))) +
   geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  labs(fill = "Hébergement en MECS") +
  ggtitle("Âge 18 ans à plus")+ theme(text = element_text(family = "Times"), legend.position = "bottom") 

require(ggpubr)
ggarrange(g1,g2,g3,g4,g5,g6, common.legend = T)
```


```{r}
require(svyr)
e_mecsw3 <- e_mecs %>% subset(MNA == "Non") %>% 
  as_survey_design(ids = 1, weight  = poids2)

g1 <- e_mecsw3 %>% subset(age_ed == "0_3") %>% 
  drop_na(any_of(vars)) %>% 
  ggsurvey() +
  aes(x = ARES_rec, fill = HEBE_rec3, label = f(after_stat(prop))) +
  geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  ggtitle("Âge 0 à 3 ans")+ theme(text = element_text(family = "Times"),legend.position="none")

g2 <- e_mecsw3 %>% subset(age_ed == "4_6") %>% 
  drop_na(any_of(vars)) %>% 
  ggsurvey() +
  aes(x = ARES_rec, fill = HEBE_rec3, label = f(after_stat(prop))) +
  geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  ggtitle("Âge 4 à 6 ans")+ theme(text = element_text(family = "Times"),legend.position="none")

g3 <- e_mecsw3 %>% subset(age_ed == "7_12") %>% 
  drop_na(any_of(vars)) %>% 
  ggsurvey() +
  aes(x = ARES_rec, fill = HEBE_rec3, label = f(after_stat(prop))) +
   geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  ggtitle("Âge 7 à 12 ans")+ theme(text = element_text(family = "Times"),legend.position="none")

g4 <-e_mecsw3 %>% subset(age_ed == "13_14") %>% 
  drop_na(any_of(vars)) %>% 
  ggsurvey() +
  aes(x = ARES_rec, fill = HEBE_rec3, label = f(after_stat(prop))) +
   geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  ggtitle("Âge 13 à 14 ans")+ theme(text = element_text(family = "Times"),legend.position="none")

g5 <-e_mecsw3 %>% subset(age_ed == "15_17") %>% 
  drop_na(any_of(vars)) %>% 
  ggsurvey() +
  aes(x = ARES_rec, fill = HEBE_rec3, label = f(after_stat(prop))) +
   geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  ggtitle("Âge 15 à 17 ans")+ theme(text = element_text(family = "Times"),legend.position="none")

g6 <-e_mecsw3 %>% subset(age_ed == "18_+") %>% 
  drop_na(any_of(vars)) %>% 
  ggsurvey() +
  aes(x = ARES_rec, fill = HEBE_rec3, label = f(after_stat(prop))) +
   geom_bar(position = "fill", width = 0.3) +
  ylab("") +
  xlab("") +
  scale_y_continuous(labels = function(x) paste0(x * 100, '%')) +
  scale_fill_manual(values = met.brewer("Egypt")) +
  theme_bw() +
  labs(fill = "Hébergement en MECS") +
  ggtitle("Âge 18 ans à plus")+ theme(text = element_text(family = "Times"), legend.position = "bottom") 

g6_leg <- get_legend(g6)

require(ggpubr)
ggarrange(g1,g2,g3,g4,g5,g6, common.legend = T, legend.grob = g6_leg) + theme(text= element_text())
```
# Modèle sur orientation à l'entrée en MECS

```{r}
## Recodage de e_mecs$ARES_rec en e_mecs$ARES_na
e_mecs$ARES_na <- e_mecs$ARES_rec %>%
  fct_explicit_na("NULL")
## Recodage de e_mecs$ARES_na
e_mecs$ARES_na <- e_mecs$ARES_na %>%
  fct_recode(
    NULL = "NULL")

e_mecs$MES_na <- e_mecs$MES_rec %>%
  fct_recode(
    NULL = "NA")


e_mecs$ARES_na2 <- recode_res(e_mecs$ARES)

modele <- e_mecs %>% select(poids_enf, SEX, MNA, HAND, age_ed, age_pp, MES_na, HEBE_rec2,HEBE_rec3, ARES_na, ARES_na2)
modele %<>% drop_na()

modele %>% tbl_summary(include = c(SEX, MNA, HAND, age_ed, MES_na, ARES_na2),
                    by = HEBE_rec3,
                    missing = "no",
                    statistic = list(all_categorical() ~ "{n}")) %>%   
  modify_header(label = "") %>% 
  bold_labels()

modele$poids2 <- modele$poids_enf/mean(modele$poids_enf)
modelesw <- svydesign(ids = ~1, data = modele, weights = ~ modele$poids2)


require(nnet)
m1 <- multinom(HEBE_rec2 ~ age_ed + SEX + MNA + HAND, data = modele)
mw <- multinom(HEBE_rec2 ~ age_ed + SEX + MNA + HAND, data = modele, weights = poids2)

m1 %>% tbl_regression(exponentiate = TRUE) %>% 
  add_significance_stars(hide_se = TRUE, hide_ci = TRUE) %>%
  modify_header(label = "**Référence : Collectif**") %>%
  modify_caption("Modèle 1 réduit : type d'hébergement à la sortie de MECS")  %>% 
  modify_column_hide("ci") %>% 
  bold_labels()%>%
  multinom_pivot_wider()


mw %>% tbl_regression(exponentiate = TRUE) %>% 
  add_significance_stars(hide_se = TRUE, hide_ci = TRUE) %>%
  modify_header(label = "**Référence : Collectif**") %>%
  modify_caption("Modèle pondéré")  %>% 
  modify_column_hide("ci") %>% 
  bold_labels()%>%
  multinom_pivot_wider()

m2w <- multinom(HEBE_rec2 ~ age_ed + SEX + MNA + HAND + MES_na, data = modele, weights = poids2)
m2w %>% tbl_regression(exponentiate = TRUE) %>% 
  add_significance_stars(hide_se = TRUE, hide_ci = TRUE) %>%
  modify_header(label = "**Référence : Collectif**") %>%
  modify_caption("Modèle pondéré")  %>% 
  modify_column_hide("ci") %>% 
  bold_labels()%>%
  multinom_pivot_wider()

m3w <- multinom(HEBE_rec2 ~ age_ed + SEX + MNA + MES_na + ARES_na, data = modele, weights = poids2)
step(m3w)
m3w %>% tbl_regression(exponentiate = TRUE) %>% 
  add_significance_stars(hide_se = TRUE, hide_ci = TRUE) %>%
  modify_header(label = "**Référence : Collectif**") %>%
  modify_caption("Modèle pondéré")  %>% 
  modify_column_hide("ci") %>% 
  bold_labels()%>%
  multinom_pivot_wider()


m4w <- multinom(HEBE_rec2 ~ age_ed + SEX + MNA  + ARES_na, data = modele, weights = poids2)

m4w %>% tbl_regression(exponentiate = TRUE) %>% 
  add_significance_stars(hide_se = TRUE, hide_ci = TRUE) %>%
  modify_header(label = "**Référence : Collectif**") %>%
  modify_caption("Modèle pondéré")  %>% 
  modify_column_hide("ci") %>% 
  bold_labels()%>%
  multinom_pivot_wider()
```
