---
title: "I.A.Populartion Hétérogène"
author: "Élodie Lemaire"
date: '2022-06-04'
output:
    pdf_document:
    latex_engine: lualatex
header-includes:
  - \usepackage[normal,labelfont=bf]{caption}
  - \usepackage[bottom]{footmisc}
  - \usepackage{mdframed}
bibliography: essai.bib
linestretch: 1.25
fontsize: 11
mainfont: Times
urlcolor: blue
lang: fr
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE,fig.align = 'center')

library(pacman)
p_load(tidyverse,knitr,questionr,readxl,survey,gtsummary, rstatix, magrittr, #Pour analyses et manipulation
       ggcharts, huxtable, #pour les tableaux
       GGally, extrafont, wesanderson) #pour les graphiques
theme_gtsummary_language("fr", decimal.mark = ",", big.mark = " ")

source("Recodage.R")
```


```{r tab1}

enfw %>% tbl_svysummary(include = c(CATEG_rec,SEX, MNA, age_ed, HAND),
                    by = CATEG_rec,
                    percent = "col", 
                    statistic = list(all_categorical() ~ "{p} ({n_unweighted})"),
                    missing = "no") %>%   
  modify_header(label = "") %>% 
  bold_labels() %>% 
  as_hux_table() %>% 
  add_footnote("Source : ES-PE 2017.") %>%
  add_footnote("Champ : Sur les 18 440 enfants présents en MECS au 12/12/2017.") %>%
  set_number_format(NA) %>% 
  set_caption("Résultats de la classification")
```



## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
recode_mes2 <- function(var) {
  var <- as.factor(var)
  var_rec <- fct_recode(var, 
                        "Mes admin Min" = "02",
                        "Mes admin Maj" = "03",
                        "Judi conf" = "04",
                        "Judi direct" = "09",
                        "Judi direct" = "10",
                        "Judi direct" = "11",
                        "Judi direct" = "12",
                        "Judi direct" = "13",
                        "MO" = "14",
                        "MO" = "15",
                        "MO" = "16",
                        "Mes respo par" = "01",
                        "Mes respo par" = "17",
                        "Mes respo par" = "05",
                        "Mes respo par" = "06",
                        "Mes respo par" = "07",
                        "Mes respo par" = "08",
                        "Autre" = "18",
                        "Autre" = "19",
                        "NA" = "")
  return(var_rec)
}



enf$MES_rec <- recode_mes2(enf$MES)

## Réordonnancement de enf$MES_rec
enf$MES_rec <- enf$MES_rec %>%
  fct_relevel(
    "Mes admin Min", "Mes admin Maj", "Judi conf", "Judi direct",
    "Mes respo par", "MO", "Autre", "NA"
  )
## Réordonnancement de enf$CATEG_rec
enf$CATEG_rec <- enf$CATEG_rec %>%
  fct_relevel(
    "MECS", "Foyers", "Lieux de vie", "Villages", "Pouponnières"
  )
enfw <- svydesign(ids = ~1, data = enf, weights = ~ enf$poids2)


enfw %>% tbl_svysummary(include = c(MES_rec, CATEG_rec),
                    by = CATEG_rec,
                    percent = "col", 
                    statistic = list(all_categorical() ~ "{p}"),
                    missing = "no") %>%   
  modify_header(label = "") %>% 
  bold_labels() %>%
  add_p()

mecs <- subset(enf, CATEG_rec == "MECS")
mecs %>% tbl_summary(include = c(SEX, MNA),
                    by = MNA,
                    percent = "col", 
                    statistic = list(all_categorical() ~ "{p}"),
                    missing = "no") %>%   
  modify_header(label = "")



enfw %>% tbl_svysummary(include = c(dur_dpla, CATEG_rec),
                    by = CATEG_rec,
                    percent = "col", 
                    statistic = list(all_continuous() ~ "Q1 : {p25}, Med : {median}, Moy : {mean}, Q3 : {p75}"),
                    missing = "no") %>%   
  modify_header(label = "")
```


```{r}
enf_12 <- read_sas("ES-PE 2017/enf_enf.sas7bdat")

enf_12$CAT<- recode_categ(enf_12$CAT)
enf_12$CAT<- recode_categ_chr(enf_12$CAT)

enf_12 %<>% mutate(age = (2017 - as.numeric(ANN)))

enf_12$age_ed <-recode_age(enf_12$age)


enf_12$POIDS2 <- enf_12$POIDS/mean(enf_12$POIDS)
enf_12w <- svydesign(ids = ~1, data = enf_12, weights = ~ enf_12$POIDS2)

enf_12w %>% tbl_svysummary(include = c(CAT,SEX, age_ed, HAND),
                    by = CATEG_rec,
                    percent = "col", 
                    statistic = list(all_categorical() ~ "{p}"),
                    missing = "no") %>%   
  modify_header(label = "") %>% 
  bold_labels()
```

