---
output: 
  pdf_document:
    includes:
      in_header: MEP.tex
    number_sections: true
    latex_engine: xelatex
documentclass: report
linestretch: 1.5
fontsize: 12
mainfont: Times New Roman
geometry: margin=2.5cm
papersize: a4
bibliography: Biblio.bib
csl: le-tapuscrit-note.csl
---
\pagestyle{empty}

```{r setup intro, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{=tex}
\phantomsection
\addcontentsline{toc}{chapter}{Introduction}
\chapter*{\huge Introduction}
```
\title{Introduction}


|               Dans un champ aux sources de données nombreuses et fragmentées, l’enquête auprès des établissements et services de la protection de l’enfance (ES-PE) a permis en 2017 à la Direction de la Recherche, des Études, de l'Évaluation et des Statistiques (DREES) de réaliser un bilan national de l’action de ces établissements sociaux. L’enquête a ainsi révélé que 61 000 enfants ou adolescents étaient alors hébergés au sein des structures de l’Aide sociale à l’enfance (ASE), représentant ainsi un tiers des enfants placés sous la protection de l’enfance[^1]. Les chiffres publiés en mai 2020 sont globalement encourageants pour la Protection de l’enfance : un taux d’occupation de 95%, 97% des jeunes hébergés scolarisés, un accroissement régulier depuis les vagues d’enquête de 2008 et 2012 des places d’hébergements, et aussi une plus grande diversité par rapport à 2012 dans l’offre des hébergements permettant une meilleure adaptation de l’accueil aux problématiques individuelles[@abassi61000Enfants2020]. Ces chiffres dressent un constat de la Protection de l’enfance loin de l’image pourtant dépeinte au cours des polémiques de ces dernières années sur les défaillances de l’ASE.

En France, la Protection de l’enfance est définie par l’article L. 112-3 du code de l’action sociale et des familles[^2]:

« *La protection de l'enfance vise à garantir la prise en compte des besoins fondamentaux de l'enfant, à soutenir son développement physique, affectif, intellectuel et social et à préserver sa santé, sa sécurité, sa moralité et son éducation, dans le respect de ses droits. Elle comprend des actions de prévention en faveur de l'enfant et de ses parents, l'organisation du repérage et du traitement des situations de danger ou de risque de danger pour l'enfant ainsi que les décisions administratives et judiciaires prises pour sa protection.* »

Pour accomplir toutes ces tâches, elle délègue son action aux Conseils départementaux au travers des services de l’ASE. Cette organisation a pour importante faille de créer des disparités en fonction des politiques départementales d’accueil des enfants en danger. Des polémiques anciennes, mais aussi plus récentes, comme en 2018 à l’occasion de la sortie de l’ouvrage Le Massacre des innocents, les oubliés de la République[@creoffMassacreInnocentsOublies2018] ou encore en 2020 suite à la diffusion du reportage de M6 dans l'émission Zone Interdite, intitulée : « Mineurs en danger : enquête sur les scandaleuses défaillances de l'Aide sociale à l'enfance »[^3], ont attaqué l’image de l’ASE en se demandant si parfois l’institution ne faisait pas plus de mal aux jeunes qu’elle doit protéger que leur milieu d’origine. Ces critiques ont particulièrement dénoncé des parcours de placement à l’ASE chaotiques ayant des effets négatifs sur les enfants, des jeunes qui à leur majorité se retrouvent du jour au lendemain sans aides et démunis, mais aussi des négligences d’encadrement dans les structures d’hébergement ayant pour effet la déscolarisation ou des jeunes livrés à eux-mêmes.

> *Les MECS et la désinstitutionnalisation*

Les maisons d’enfants à caractère social (MECS) sont des structures particulièrement concernées par l’ensemble de ces réflexions. Les MECS sont des établissements de placement civil relevant de l’Aide sociale à l’enfance et donc des départements. Elles accueillent 75% des enfants présents au 15 décembre 2017 dans des établissements relevant de l’ASE. Il s’agit donc du type d’établissement accueillant le plus d’enfants et étant le plus répandu sur le territoire français avec près de 1 310 structures.

Lorsque l’on s’intéresse à la Protection de l’enfance, les maisons d’enfant à caractère social (MECS) sont souvent placées au centre des critiques, tout en étant présentées comme une institution bénéficiant d’une forte capacité d’innovation[@touyaTravaillerMECS2020]. Qu’on les qualifie d’innovantes ou non, les pratiques des professionnels des MECS ont bel et bien évolué ces dernières années au travers surtout de la diversification des modes d’accueil, afin de sortir de l’accueil dit classique en internat collectif[@afquirEvolutionPriseCharge2008]. Cette démarche s’inscrit dans le cadre plus large de la désinstitutionnalisation motivée par deux impératifs en protection de l’enfance : parvenir le plus possible à maintenir le lien avec la famille et proposer un accueil des enfants plus personnalisé. 

Les réponses à ces critiques sont donc d’abord passées par la loi obligeant les institutions aux évolutions. Dans son acception étymologique, l’institution est perçue comme un processus tendant momentanément vers le maintien des normes et des pratiques. Il s’agit donc globalement d’un concept très large. Jacques Revel a proposé néanmoins plusieurs définitions allant de la plus restrictive à la plus large. La première arrête l’institution à sa dimension juridico-politique. La seconde l’élargit à tout type d’organisation « fonctionnant de façon régulière dans la société, selon des règles explicites et implicites, et dont on présume qu’elle répond à une demande collective particulière ». La dernière est la plus large est englobe toute organisation « sociale qui lie des valeurs, des normes, des modèles de relations et de conduites, des rôles »[@revelInstitutionSocial2006]. Nous prendrons appui sur la deuxième définition.

À partir de la fin de la Seconde Guerre mondiale et jusqu’au début des années 2000 on observe un double mouvement de structuration et de légitimation du travail social avec une professionnalisation croissante des acteurs, mais aussi un mouvement qualifié d’institutionnalisation des structures résultant des différentes politiques sociales menées sur le territoire[@hirletCeQueDesinstitutionnalisation2017]. L’Aide sociale à l’enfance, pilotée depuis les années 1980 par les départements, voit ses établissements se développer dans ce contexte et particulièrement les Maisons d’enfant à caractère social (MECS).

Par désinstitutionnalisation, on entendrait ainsi au sens commun la sortie des publics accueillis des structures enfermantes d’accueil et le passage à des prises en charge de proximité. Les lois de 2002 et 2007 devaient justement faire évoluer la protection de l’enfance en ce sens. Pour autant en 2009, la Commission européenne percevait toujours la protection de l’enfance en France comme relevant encore trop de la « culture institutionnelle ». Cette dernière se caractérise par une tenue à l’écart des bénéficiaires, une dépersonnalisation et une rigidité de la routine dans les structures d’accueil, et enfin, une éthique de soin paternaliste au lieu d’interactive. Au travers des lois de 2002 et 2007, il s’agissait justement dans un contexte d’individualisation de la société, de proposer des projets d’accueil personnalisés et de réaffirmer le droit parental dans la mesure où les droits des enfants restent protégés[^4].

[^4]: Rapport du groupe d’experts ad hoc sur la transition des soins en institution aux soins de proximité – Commission européenne, Direction générale de l’emploi, des affaires sociales et de l’égalité des chances – septembre 2009.

Pour les défenseurs du dispositif de protection de l’enfance français, la France bénéficierait de sa propre « culture institutionnelle » incomprise par la Commission européenne. En effet, une des spécificités du système française est que « l’institution est à la fois un lieu et une réponse de protection »[@calmoDesinstitutionnalisationProtectionEnfance2012]. Du fait des lois de 2002 et 2007, l’accueil en établissement relevant de l’Aide sociale à l’enfance répond pour la Convention Nationale des Associations de Protection de l’enfant (CNAPE) aux objectifs de désinstitutionalisation promus par la Commission européenne en proposant un « accompagnement souple et adapté » visant à répondre « au plus près des besoins de l’enfant confié ou accueilli »[@calmoDesinstitutionnalisationProtectionEnfance2012]. Bien loin, donc de l'institution totale au sens de Goffman[@goffmanAsilesEtudesCondition1968]. Pour d’autres pourtant, quand bien même ces lois sont une avancée vers la désinstitutionnalisation – et surtout une meilleure prise en charge des enfants placés –, elles sont mises en œuvre dans un cadre institutionnel à l’aide d’une bureaucratie pesante faisant perdurer la rigidité des dispositifs d’accueil et leur difficile adaptabilité[@verdierVousAvezDit2013]. D’un problème politique, la question est devenue scientifique, avec la multiplication d’études depuis les années 1980 sur le devenir des enfants placés et donc les effets à termes de la prise en charge par la Protection de l’enfance.

> *La question du devenir des enfants placés au cœur de la littérature scientifique*

Depuis de nombreuses années, la littérature scientifique s'est attachée à étudier l'ASE et les effets du placement sur les enfants et leur devenir. En 1988, un appel à la recherche sur le devenir des enfants placés lancé par Corbillon, Assailly, et Duyme a clairement énoncé la nécessité de ce type d'études jusqu'alors manquantes : « Le devenir à l'issue du placement est un sujet pratiquement inconnu. Il s'agit pourtant d'une donnée essentielle pour l'appréciation et l'amélioration du service rendu, mais aussi pour la connaissance d'une population »[@corbillonAideSocialeEnfance1988]. Les recherches ont dès lors étoffé les connaissances scientifiques sur le sujet. Pourtant, les données sur les enfants placés sont difficilement accessibles, voire manquantes, du fait de peu de statistiques existantes dédiées à autre chose que la « visée gestionnaire », mais aussi d'un système de protection de l'enfance divisé en deux secteurs (judiciaire et administratif), impliquant deux sources statistiques différentes dans lesquelles on peut retrouver les mêmes enfants [@frechonImpossibleObservationEnfance2002]. L'étude ELAP -- Étude Longitudinale sur l'accès à l'Autonomie après le Placement -- de l'INED, réalisée entre 2013 et 2019, a permis de bâtir des données dédiées à la recherche permettant justement de faire un point sur les conditions de vie des jeunes au moment de la fin de la prise en charge, mais aussi sur les conséquences du placement à l'âge adulte.

En attendant la mise en place de l'enquête ELAP, les chercheurs se sont servis des données d'autres enquêtes pour aborder la question du devenir des enfants placés et notamment des chiffres sur les sans domiciles des enquêtes de l'INED de 1995 et 1998 et de l'INSEE de 2001 \\footnote{Particulièrement étudié par Isabelle Frechon et Maryse Marpsat, « Placement dans l'enfance et précarité de la situation de logement », *Economie et statistique*, 1 septembre 2016, vol. 2016, p. 37‑68.}. Bien qu'aucun lien de causalité ne soit formellement prouvable entre le fait d'avoir été placé et la vulnérabilité à l'âge adulte, étant donné que de multiples facteurs peuvent expliquer ce dernier, le placement semble être néanmoins « un indicateur synthétique de l'ensemble de ces difficultés » [@frechonTrajectoiresPriseCharge2013]. Les études se sont aussi concentrées sur des profils particuliers d'enfants ayant vécu un placement, comme les orphelins placés et leurs difficultés à l'âge adulte [@frechonJeunesOrphelinsPlaces2020]. Cet ensemble de recherches, brièvement résumé, permet d'explorer les éventuelles conséquences d'un placement une fois l'enfant devenu adulte, mais on peut supposer que tout dépend du parcours de placement vécu par l'enfant.

> *L'importance du maintien du lien avec la famille*

Maintenir le lien social avec la famille est en effet un enjeu pour le devenir de l’enfant à la sortie de la protection de l’enfance. L’étude de Isabelle Frechon et Marpsat a démontré le poids de l’absence des liens sociaux dans les situations de précarité de logement pour les jeunes ayant connu un placement en protection de l’enfance. Plus particulièrement, elles démontrent que les autres liens sociaux – lien amical, lien de participation organique entre acteurs de la vie professionnelle, lien de citoyenneté – ne compensent pas l’absence d’un lien familial, le rendant particulièrement important pour le devenir de ces enfants[@frechonPlacementDansEnfance2016].

En ce sens, l’attitude de la protection de l’enfance d’écarter totalement la famille des parcours de placement a été souvent critiquée et rapprochée du processus de disqualification social de Serge Paugam.  Ce dernier « renvoie au processus d’affaiblissement ou de rupture des liens de l’individu à la société au sens de la perte de la protection et de la reconnaissance sociale » (p.113). La disqualification parentale, définit par Serge Paugam, peut être comprise soit comme une dimension de la disqualification social compte tenu qu’elle peut en être une conséquence, dans les situations où la pauvreté pèse sur les capacités à assumer les fonctions parentales. Mais elle peut aussi être comprise comme un processus à part entière pour Serge Paugam si on s’intéresse particulièrement à la question du lien de filiation. Et en ce sens, la protection de l’enfance est productrice de disqualification parentale lorsqu’elle retire l’exercice des fonctions parentales même temporairement aux parents. Il y a donc suspension temporaire du lien de filiation, ce qui entraîne la remise en cause des parents autant dans leur capacité parentale que dans leur statut. Les conséquences de cette suspension seront différentes en fonction de l’intégration des parents par les professionnels dans la prise en charge de leur enfant, mais souvent, et quand bien même la loi encourage et invite à cette participation, les professionnels oscillent entre l’accompagnement social et la sanction[@paugamEpreuveDisqualificationParentale2014].

> *La nécessité d'une prise en charge personnalisée et stable*

Nombre d'études[^4] ont aussi porté sur une question que se posaient les chercheurs et les professionnels du secteur sur les conséquences des parcours difficiles de placement. Elles ont eu pour conclusion que plus que la durée de prise en charge « c'est la multiplicité des placements qui a une influence négative sur l'insertion sociale et professionnelle »[@frechonTrajectoiresPriseCharge2013], permettant d'alerter les pouvoirs publics sur la nécessité de proposer aux enfants placés des parcours les plus pérennes possible avec une prise en charge ajustée à chaque enfant. En ce sens, les mineurs isolés étrangers (MIE) ou mineurs non accompagnés (MNA), arrivés sur le territoire depuis la fin des années 1990, ont constitué aussi une population particulière à étudier révélant les failles de l'Aide sociale à l'enfance, voire leur incapacité à proposer une aide adaptée à des profils que l'institution n'est pas préparée à traiter [@helfterPriseChargeMineurs2010].

En ce sens, des études se sont concentrées sur le processus de placement en mettant le ressenti de l'enfant au cœur de leur préoccupation. Par exemple, Émilie Potin s'est attachée au cours de sa thèse à décrire le processus de placement en plusieurs phases : « Le parcours de placement est traversé par trois phases distinctes : la désignation du danger (processus d'étiquetage) ; le déplacement d'un lieu à l'autre et d'un milieu social à l'autre (processus d'apprentissage, d'adaptation et de socialisation) ; l'intégration dans le quotidien du placement (phase de routinisation) » [@potinEnfantsDangerEnfants2009]. Le processus d'étiquetage appelle par la suite à un déplacement dans une structure. L'ASE, à l'aide de l'étiquette attribuée à la situation de l'enfant, appelle ensuite les structures qu'elle juge adaptées à accueillir l'enfant afin d'appliquer la décision de protection. Les structures elles-mêmes acceptent ou non d'accueillir l'enfant en fonction de leur propre jugement en leur capacité d'accueillir l'enfant, leurs places disponibles et le public déjà accueilli. Cette chaîne de décision s’ouvre ainsi à l’étude à l’aide de cette littérature déjà prolixe.

> *L'enquête ES-PE : des données à visée gestionnaire tentant d'intégrer des questions scientifiques*

Toute cette littérature tend à valider dans une certaine mesure les critiques émises à l'encontre de la protection de l'enfance et à aller dans le sens de l'évolution de l'institution vers un processus de désinstitutionnalisation. Cette dernière se focaliserait justement sur les types d'hébergements proposés aux enfants placés. On peut concrètement sa mise en œuvre dans le développement des logements autonomes, appelés aussi hébergements éclatés, des mesures d'accueil en milieu ouvert, ou encore, la mise en place d'accueil séquentiel ou diversifié qui permet l'hébergement en internat collectif de l'enfant quelques jours par semaine. Malgré ces évolutions, il n'existe pour autant pas de grands principes clairement édictés sur la répartition entre ces différents hébergements des enfants placés et c'est au travers des données à l'échelle nationale produites par les établissements eux-mêmes que nous avons le plus de chances d'observer cette tendance. Il faut aussi comprendre que ces évolutions dépendent de questions économiques permettant l'ouverture de nouveaux types d'hébergements et donc concrètement des places disponibles pour accueillir ces enfants. Ainsi, il y aurait une tension entre personnalisation de l'accompagnement et logiques gestionnaires qui guiderait les principes de répartition entre hébergements.

L’enquête auprès des établissements et services de la protection de l’enfance (ES-PE) apparaît ainsi la mieux armée pour répondre à ces questions. En effet, elle est réalisée directement auprès de ces établissements, à l’échelle de la France entière (DOM-TOM compris, sauf Mayotte). Elle comporte néanmoins de nombreuses limites. Cette enquête avait été à l’origine construite dans une visée gestionnaire et la version 2017 a largement intégrée des questions relevant de considérations scientifiques. Pour autant, ces dernières sont contraignantes du fait de leur formulation, de leurs modalités de réponse, et régulièrement par l’impossibilité de pousser plus loin les analyses par manque de données complémentaires. C’est néanmoins sur cette enquête que nous bâtirons cette recherche en nous demandant \footnote{Ce mémoire a été réalisé sur R Markdown, l'intégralité des analyses sont disponibles sur Github au lien suivant : \url{https://github.com/ElodieXVI/Memoire-M2}. Pour assurer la reproductibilité des analyses, le package Renv a aussi été employé. Il permet d'effectuer une capture du système d'exploitation, des mises à jour de R et de RStudio ainsi que de l'ensemble des packages employés. Ainsi, même si des mises à jour sont effectuées sur R, RStudio ou n'importe lequel des packages employés rendant impossible l'analyse, à l'aide de Renv il est possible de restaurer les versions utilisées pour reproduire les analyses de ce mémoire.}:

> Que nous enseignent les données de l'enquête ES-PE 2017 sur la désinstutionalisation à l'œuvre dans les maisons d'enfant à caractère sociale au travers de l'orientation entre hébergements des enfants placés ?

Pour répondre à cette question, nous présenterons tout d'abord le fonctionnement de la Protection de l'enfance et des Maisons d'enfant à caractère sociale. Nous verrons par la suite comment cette organisation affecte la production de données sur le sujet de l'enfance protégé en participant notamment à une fragmentation des données disponibles, ce qui nous permettra d'introduire plus précisément l'enquête auprès des établissements sociaux de la Protection de l'enfance menée par la DREES, ses limites et la population hétérogène sur laquelle elle nous renseigne. Par la suite, nous présenterons en deux temps les résultats de nos analyses : tout d'abord, nous chercherons à l'aide de nos données à étudier les critères de répartition entre les hébergements en MECS qui sont à la fois des critères individuels relevant des profils des enfants placés, mais aussi des critères relevant de logiques gestionnaires, à savoir la place disponible dans les différents hébergements. Ceci nous permettra ainsi de percevoir ce qui relève de la logique gestionnaire et ce qui relève de la personnalisation du placement. Enfin, nous chercherons à développer les réponses obtenues en replaçant le passage dans un hébergement en MECS dans le cadre plus large du parcours de placement en protection de l'enfance. Ceci va nous permettre de construire une typologie des types de placements et de les confronter aux différents critères d'orientation entre les hébergements.

[^1]: DREES, Les bénéficiaires de l'Aide Sociale à l'enfance -- 31/12/2017.

[^2]: https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000045136781, consulté le 11/05/2022

[^3]: Zone Interdite, « Mineurs en danger : enquête sur les scandaleuses défaillances de l'Aide sociale à l'enfance », diffusé le 25/03/2020.

[^4]: Michel Corbillon et al., *L'enfant placé : de l'Assistance publique à l'Aide sociale à l'enfance*, Paris, Ministère de la solidarité, de la santé et de la protection sociale, 1990, 208 p ; Francis Mouhot, « Le devenir des enfants. De l'aide sociale à l'enfance », *Devenir*, 2001, Vol. 13, n^o^ 1, p. 31‑66 ; Daniel Rousseau et al., « Devenir à long terme de très jeunes enfants placés à l'Aide sociale à l'enfance », *Revue francaise des affaires sociales*, 15 juin 2016, n^o^ 1, p. 343‑374.
